// Code generated by Kitex v0.5.2. DO NOT EDIT.

package peopleservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	orbital "github.com/simbayippy/OrbitalxTiktok/RPCservers/kitex_gen/orbital"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	EditPerson(ctx context.Context, person *orbital.Person, callOptions ...callopt.Option) (r *orbital.Person, err error)
	Echo(ctx context.Context, req *orbital.Request, callOptions ...callopt.Option) (r *orbital.Response, err error)
	EditPerson2(ctx context.Context, person *orbital.Person, callOptions ...callopt.Option) (r *orbital.Person, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kPeopleServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kPeopleServiceClient struct {
	*kClient
}

func (p *kPeopleServiceClient) EditPerson(ctx context.Context, person *orbital.Person, callOptions ...callopt.Option) (r *orbital.Person, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.EditPerson(ctx, person)
}

func (p *kPeopleServiceClient) Echo(ctx context.Context, req *orbital.Request, callOptions ...callopt.Option) (r *orbital.Response, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Echo(ctx, req)
}

func (p *kPeopleServiceClient) EditPerson2(ctx context.Context, person *orbital.Person, callOptions ...callopt.Option) (r *orbital.Person, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.EditPerson2(ctx, person)
}
