// Code generated by Kitex v0.6.0. DO NOT EDIT.

package mock

import (
	"context"
	"fmt"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	protopackage "github.com/simbayippy/OrbitalxTiktok/APIGateway/kitex_gen/protopackage"
	proto "google.golang.org/protobuf/proto"
)

func serviceInfo() *kitex.ServiceInfo {
	return mockServiceInfo
}

var mockServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "Mock"
	handlerType := (*protopackage.Mock)(nil)
	methods := map[string]kitex.MethodInfo{
		"Test": kitex.NewMethodInfo(testHandler, newTestArgs, newTestResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "protopackage",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.6.0",
		Extra:           extra,
	}
	return svcInfo
}

func testHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(protopackage.MockReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(protopackage.Mock).Test(ctx, req)
		if err != nil {
			return err
		}
		if err := st.SendMsg(resp); err != nil {
			return err
		}
	case *TestArgs:
		success, err := handler.(protopackage.Mock).Test(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*TestResult)
		realResult.Success = success
	}
	return nil
}
func newTestArgs() interface{} {
	return &TestArgs{}
}

func newTestResult() interface{} {
	return &TestResult{}
}

type TestArgs struct {
	Req *protopackage.MockReq
}

func (p *TestArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(protopackage.MockReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *TestArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *TestArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *TestArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, fmt.Errorf("No req in TestArgs")
	}
	return proto.Marshal(p.Req)
}

func (p *TestArgs) Unmarshal(in []byte) error {
	msg := new(protopackage.MockReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var TestArgs_Req_DEFAULT *protopackage.MockReq

func (p *TestArgs) GetReq() *protopackage.MockReq {
	if !p.IsSetReq() {
		return TestArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *TestArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *TestArgs) GetFirstArgument() interface{} {
	return p.Req
}

type TestResult struct {
	Success *protopackage.StringResponse
}

var TestResult_Success_DEFAULT *protopackage.StringResponse

func (p *TestResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(protopackage.StringResponse)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *TestResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *TestResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *TestResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, fmt.Errorf("No req in TestResult")
	}
	return proto.Marshal(p.Success)
}

func (p *TestResult) Unmarshal(in []byte) error {
	msg := new(protopackage.StringResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *TestResult) GetSuccess() *protopackage.StringResponse {
	if !p.IsSetSuccess() {
		return TestResult_Success_DEFAULT
	}
	return p.Success
}

func (p *TestResult) SetSuccess(x interface{}) {
	p.Success = x.(*protopackage.StringResponse)
}

func (p *TestResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *TestResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Test(ctx context.Context, Req *protopackage.MockReq) (r *protopackage.StringResponse, err error) {
	var _args TestArgs
	_args.Req = Req
	var _result TestResult
	if err = p.c.Call(ctx, "Test", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
