// Code generated by Kitex v0.6.0. DO NOT EDIT.

package bizservice

import (
	server "github.com/cloudwego/kitex/server"
	http "github.com/simbayippy/OrbitalxTiktok/RPCservers/kitex_gen/http"
)

// NewInvoker creates a server.Invoker with the given handler and options.
func NewInvoker(handler http.BizService, opts ...server.Option) server.Invoker {
	var options []server.Option

	options = append(options, opts...)

	s := server.NewInvoker(options...)
	if err := s.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	if err := s.Init(); err != nil {
		panic(err)
	}
	return s
}
