// Code generated by Kitex v0.5.2. DO NOT EDIT.

package peoplesservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	orbital2 "github.com/simbayippy/OrbitalxTiktok/APIGateway/kitex_gen/orbital2"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	EditPerson(ctx context.Context, Req *orbital2.Person, callOptions ...callopt.Option) (r *orbital2.Person, err error)
	Echo(ctx context.Context, Req *orbital2.Request, callOptions ...callopt.Option) (r *orbital2.Response, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kPeoplesServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kPeoplesServiceClient struct {
	*kClient
}

func (p *kPeoplesServiceClient) EditPerson(ctx context.Context, Req *orbital2.Person, callOptions ...callopt.Option) (r *orbital2.Person, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.EditPerson(ctx, Req)
}

func (p *kPeoplesServiceClient) Echo(ctx context.Context, Req *orbital2.Request, callOptions ...callopt.Option) (r *orbital2.Response, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Echo(ctx, Req)
}
